### ISSUE TITLE
Flos Roadmap

### ISSUE THREAD

**Issue by flowirtz** [FWirtz/SCANdal#1]
Soooooooo here we go, day 2!
- [x] expose interfaces for dogl etc. !!!
- [x] set onClick listeners
- [X]  ~~move JS out to ext. file (forget about that, seriously... Readability: NO GO! :wink:)~~
- [ ]  fill the details file
- [x]  call details accordingly
- [x]  make it go back :) (BACK BUTTON!)
- [X] Add coupon
- [ ]  test it (ha!)
